import dotenv from "dotenv";
import mongoose from "mongoose";
import EmailTemplate from "../models/EmailTemplate";

dotenv.config({ path: ".env" });

const CONTACT_TEMPLATE = {
  templateName: "contact_notification",
  subject: "[PDO-DAICU] New Contact Inquiry from {{name}}",
  html: `<div style="font-family: Arial, sans-serif; background:#f6f6f6; padding:24px;">
  <div style="max-width:640px; margin:0 auto; background:#ffffff; border-radius:12px; overflow:hidden; border:1px solid #e5e5e5;">
    <div style="background:#662b2c; color:#ffffff; padding:20px 24px;">
      <h2 style="margin:0; font-size:22px;">PDO-DAICU Contact Form</h2>
      <p style="margin:6px 0 0; font-size:14px;">New inquiry received from the website</p>
    </div>
    <div style="padding:24px; color:#2b2b2b;">
      <p style="margin-top:0;">A new contact form submission has been received. Please review the details below.</p>
      <div style="background:#f9faf9; border:1px solid #e0e0e0; border-radius:8px; padding:16px; margin:20px 0;">
        <p style="margin:0 0 10px;"><strong>Reference No.:</strong> {{referenceNumber}}</p>
        <p style="margin:0 0 10px;"><strong>Submitted At:</strong> {{submittedAt}}</p>
        <p style="margin:0 0 10px;"><strong>Name:</strong> {{name}}</p>
        <p style="margin:0 0 10px;"><strong>Email:</strong> <a href="mailto:{{email}}" style="color:#662b2c;">{{email}}</a></p>
        <p style="margin:0;"><strong>Source:</strong> PDO-DAICU Contact Us Form</p>
      </div>
      <h3 style="margin-bottom:8px; color:#662b2c;">Message</h3>
      <div style="background:#ffffff; border-left:4px solid #662b2c; padding:14px 16px; line-height:1.6; color:#333333;">{{message}}</div>
      <p style="font-size:13px; color:#777777; margin-top:24px;">This email was automatically generated by the PDO-DAICU website contact system.</p>
    </div>
  </div>
</div>`,
  isActive: true,
};

const upsertTemplate = async () => {
  const mongoUri = process.env.MONGODB_URI;

  if (!mongoUri) {
    throw new Error("MONGODB_URI is missing in .env");
  }

  await mongoose.connect(mongoUri);

  await EmailTemplate.updateMany(
    { templateName: { $ne: CONTACT_TEMPLATE.templateName } },
    { $set: { isActive: false } }
  );

  const template = await EmailTemplate.findOneAndUpdate(
    { templateName: CONTACT_TEMPLATE.templateName },
    { $set: CONTACT_TEMPLATE },
    { returnDocument: "after", upsert: true }
  );

  console.log(`Email template upserted: ${template.templateName}`);
};

upsertTemplate()
  .catch((error) => {
    console.error("Failed to upsert contact email template:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.disconnect();
  });
